name: pretty-print-precedence

dependencies:
  - base >= 4.11 && < 5.0
  - recursion-schemes >= 5.0 && < 5.1
  - pretty >= 1.1 && < 1.2
  - QuickCheck >= 2.11 && < 2.12
  - criterion >= 1.4 && < 1.5

executable:
  main: Main.hs
  source-dirs: .
